using OdinJuliaAnalysis

AnalysisSettings(
    :default,
    Fail,
    AnalysisThresholds(90, 100, 120, 20, 30, 5, 10, 15, 15),
    [
        ScanProfile(:default, String[]),
        ScanProfile(:all, String[]),
        ScanProfile(:aspirational, String[]),
    ],
    [
        RuleSetting("ARCHITECTURE-FORBIDDEN-DEPENDENCY", true, Report),
        RuleSetting("ARCHITECTURE-DEPENDENCY-CYCLE", true, Report),
        RuleSetting("ARCHITECTURE-UNRESOLVED-INTERNAL-IMPORT", true, Report),
        RuleSetting("COMMON-LINE-90", true, Warn),
        RuleSetting("COMMON-LINE-100", true, Warn),
        RuleSetting("COMMON-LINE-120", true, Fail),
        RuleSetting("COMMON-NO-TABS", true, Fail),
        RuleSetting("JULIA-SYNTAX", true, Fail),
        RuleSetting("JULIA-CLOSING-PAREN-PLACEMENT", true, Fail),
        RuleSetting("JULIA-JET-POSSIBLE-ERROR", true, Fail),
        RuleSetting("JULIA-NAMING", true, Warn),
        RuleSetting("JULIA-NONCONST-GLOBAL", true, Warn),
        RuleSetting("JULIA-UNUSED-IMPORT", true, Report),
        RuleSetting("JULIA-DECLARATION-ORDER", true, Warn),
        RuleSetting("JULIA-RETURN-TUPLE", true, Fail),
        RuleSetting("JULIA-PARAMETERS-FAIL", true, Fail),
        RuleSetting("JULIA-FUNCTION-LINES-REPORT", true, Report),
        RuleSetting("JULIA-FUNCTION-LINES-WARN", true, Warn),
        RuleSetting("JULIA-FUNCTION-LINES-FAIL", true, Fail),
        RuleSetting("JULIA-CYCLOMATIC-REPORT", true, Report),
        RuleSetting("JULIA-CYCLOMATIC-WARN", true, Warn),
        RuleSetting("JULIA-CYCLOMATIC-FAIL", true, Fail),
        RuleSetting("ODIN-SYNTAX", true, Fail),
        RuleSetting("ODIN-BUILD-FAILED", true, Fail),
        RuleSetting("ODIN-CLOSING-PAREN-PLACEMENT", true, Fail),
        RuleSetting("ODIN-NAMING", true, Warn),
        RuleSetting("ODIN-NONCONST-GLOBAL", true, Warn),
        RuleSetting("ODIN-UNUSED-IMPORT", true, Report),
        RuleSetting("ODIN-DECLARATION-ORDER", true, Warn),
        RuleSetting("ODIN-RETURN-TUPLE", true, Fail),
        RuleSetting("ODIN-PARAMETERS-WARN", true, Warn),
        RuleSetting("ODIN-PARAMETERS-FAIL", true, Fail),
        RuleSetting("ODIN-FUNCTION-LINES-REPORT", true, Report),
        RuleSetting("ODIN-FUNCTION-LINES-WARN", true, Warn),
        RuleSetting("ODIN-FUNCTION-LINES-FAIL", true, Fail),
        RuleSetting("ODIN-CYCLOMATIC-REPORT", true, Report),
        RuleSetting("ODIN-CYCLOMATIC-WARN", true, Warn),
        RuleSetting("ODIN-CYCLOMATIC-FAIL", true, Fail),
        RuleSetting("FUNCTION-METRIC-POLICY-DRIFT", true, Fail),
        RuleSetting("NAMING-POLICY-DRIFT", true, Fail),
        RuleSetting("ODIN-ALLOCATION-IMPLICIT", true, Warn),
        RuleSetting("ODIN-ALLOCATION-UNKNOWN", true, Fail),
        RuleSetting("ODIN-ALLOCATION-CONTEXT", true, Warn),
        RuleSetting("ODIN-ALLOCATION-HEAP", true, Warn),
        RuleSetting("ODIN-ALLOCATION-TEMPORARY", true, Report),
        RuleSetting("ODIN-ALLOCATION-CUSTOM", true, Report),
        RuleSetting("ODIN-ALLOCATION-DYNAMIC-GROWTH", true, Report),
        RuleSetting("ODIN-ALLOCATION-ARENA", true, Warn),
        RuleSetting("ODIN-ALLOCATION-HIDDEN", true, Warn),
        RuleSetting("ODIN-ALLOCATION-POLICY-DRIFT", true, Fail),
        RuleSetting("JULIA-DOC-MISSING", true, Fail),
        RuleSetting("ODIN-DOC-MISSING", true, Fail),
        RuleSetting("MARKDOWN-SINGLE-H1", true, Warn),
        RuleSetting("MARKDOWN-HEADING-LEVELS", true, Warn),
        RuleSetting("MARKDOWN-CODE-FENCE-LANGUAGE", true, Warn),
        RuleSetting("MARKDOWN-RELATIVE-LINK", true, Warn),
        RuleSetting("MARKDOWN-IMAGE-ALT-TEXT", true, Warn),
    ],
    NamingSettings(
        default_naming_settings().conventions,
        ReviewedNamingPolicy[
            ReviewedNamingPolicy(
                "diagnostic-convenience-constructors",
                "src/core/model.jl",
                :julia,
                :function,
                "Diagnostic",
                "Outer constructors conventionally use the constructed Julia type name.";
                minimum_matches=1,
                maximum_matches=1),
            ReviewedNamingPolicy(
                "naming-convention-constructor",
                "src/configuration/settings_types.jl",
                :julia,
                :function,
                "NamingConvention",
                "The convenience constructor uses the constructed Julia type name."),
            ReviewedNamingPolicy(
                "reviewed-naming-policy-constructor",
                "src/configuration/settings_types.jl",
                :julia,
                :function,
                "ReviewedNamingPolicy",
                "The convenience constructor uses the constructed Julia type name."),
            ReviewedNamingPolicy(
                "naming-settings-constructor",
                "src/configuration/settings_types.jl",
                :julia,
                :function,
                "NamingSettings",
                "The compatibility constructor uses the constructed Julia type name."),
            ReviewedNamingPolicy(
                "reviewed-allocation-policy-constructor",
                "src/configuration/settings_types.jl",
                :julia,
                :function,
                "ReviewedAllocationPolicy",
                "The convenience constructor uses the constructed Julia type name."),
            ReviewedNamingPolicy(
                "reviewed-complexity-constructor",
                "src/configuration/settings_types.jl",
                :julia,
                :function,
                "ReviewedComplexity",
                "The convenience constructor uses the constructed Julia type name."),
            ReviewedNamingPolicy(
                "extension-result-constructor",
                "src/core/extension_api.jl",
                :julia,
                :function,
                "ExtensionResult",
                "The convenience constructor uses the constructed Julia type name."),
            ReviewedNamingPolicy(
                "function-metric-settings-constructor",
                "src/configuration/settings_types.jl",
                :julia,
                :function,
                "FunctionMetricSettings",
                "The compatibility constructor uses the constructed Julia type name."),
            ReviewedNamingPolicy(
                "analysis-settings-constructor",
                "src/configuration/settings_types.jl",
                :julia,
                :function,
                "AnalysisSettings",
                "Compatibility constructors use the constructed Julia type name.";
                minimum_matches=3,
                maximum_matches=3),
            ReviewedNamingPolicy(
                "effective-settings-constructor",
                "src/configuration/settings_types.jl",
                :julia,
                :function,
                "EffectiveSettings",
                "The compatibility constructor uses the constructed Julia type name."),
        ]),
    JetSettings([
        JetEntryPoint(
            "analyzer-cli",
            "src/OdinJuliaAnalysis.jl",
            OdinJuliaAnalysis.main,
            (Vector{String},)),
    ]),
    OdinBuildSettings([
        OdinBuildTarget(
            "analysis-engine",
            "odin_engine",
            "odin-analysis-engine",
            ["-vet", "-strict-style", "-disallow-do", "-warnings-as-errors"]),
    ]),
    ReturnTupleSettings(2, 2),
    ParameterCountSettings(8, 5, 8),
    FunctionMetricSettings(
        default_function_metric_settings().julia_lines,
        default_function_metric_settings().odin_lines,
        default_function_metric_settings().julia_cyclomatic,
        default_function_metric_settings().odin_cyclomatic,
        ReviewedComplexity[
            ReviewedComplexity(
                "odin-closing-parenthesis-scanner",
                "odin_engine/main.odin",
                :odin,
                "check_closing_parentheses",
                :executable_lines,
                "The cohesive stack-based tokenizer pass is clearer " *
                    "as one state machine.";
                response=Report),
            ReviewedComplexity(
                "julia-declaration-naming-visitor",
                "src/julia_engine/JuliaEngine.jl",
                :julia,
                "collect_naming!",
                :cyclomatic_complexity,
                "The recursive syntax visitor keeps declaration scope " *
                    "transitions together.";
                response=Report),
        ]),
    AllocationSettings(
        KnownAllocatingProcedure[],
        [
            AllocatorSourcePattern("context.allocator", :context),
            AllocatorSourcePattern("context.temp_allocator", :temporary),
            AllocatorSourcePattern("heap.allocator()", :heap),
            AllocatorSourcePattern("data.allocator", :custom),
        ],
        ReviewedAllocationPolicy[
            ReviewedAllocationPolicy(
                "analysis-test-metrics-arena",
                "odin_engine/main_tests.odin",
                "odin_engine_test_procedure_metrics",
                :arena,
                "A test-lifetime arena owns parser fixtures and analysis results.";
                operation="arena_init_static",
                target="arena",
                certainty=:definite,
                response=Report),
            ReviewedAllocationPolicy(
                "analysis-test-allocation-arena",
                "odin_engine/main_tests.odin",
                "odin_engine_test_allocation_classification",
                :arena,
                "A test-lifetime arena owns parser fixtures and analysis results.";
                operation="arena_init_static",
                target="arena",
                certainty=:definite,
                response=Report),
            ReviewedAllocationPolicy(
                "analysis-test-syntax-arena",
                "odin_engine/main_tests.odin",
                "odin_engine_test_syntax_failure",
                :arena,
                "A test-lifetime arena owns parser fixtures and analysis results.";
                operation="arena_init_static",
                target="arena",
                certainty=:definite,
                response=Report),
            ReviewedAllocationPolicy(
                "analysis-arena-backing",
                "odin_engine/main.odin",
                "main",
                :arena,
                "One static virtual arena backs all analyzer allocations.";
                operation="arena_init_static",
                target="analysis_arena",
                certainty=:definite,
                response=Report),
        ]),
    ReportSettings(:auto, 50, 50))