using OdinJuliaAnalysis

AnalysisSettings(
    :default,
    Fail,
    AnalysisThresholds(90, 100, 120, 20, 30, 5, 10, 15, 15),
    [
        ScanProfile(:default, String[]),
        ScanProfile(:all, String[]),
        ScanProfile(:aspirational, String[]),
    ],
    [
        RuleSetting("DUPLICATE-CODE-POLICY-DRIFT", true, Fail),
        RuleSetting("FUNCTION-METRIC-POLICY-DRIFT", true, Fail),
        RuleSetting("NAMING-POLICY-DRIFT", true, Fail),
        RuleSetting("CALL-ROOT-POLICY-DRIFT", true, Fail),
        RuleSetting("SECURITY-UNSAFE-BOUNDARY", true, Report),
        RuleSetting("CALL-GRAPH-UNRESOLVED-EDGE", true, Report),
        RuleSetting("ARCHITECTURE-FORBIDDEN-DEPENDENCY", true, Report),
        RuleSetting("ARCHITECTURE-DEPENDENCY-CYCLE", true, Report),
        RuleSetting("ARCHITECTURE-UNRESOLVED-INTERNAL-IMPORT", true, Report),
        RuleSetting("COMMON-LINE-90", true, Warn),
        RuleSetting("COMMON-LINE-100", true, Warn),
        RuleSetting("COMMON-LINE-120", true, Fail),
        RuleSetting("COMMON-NO-TABS", true, Fail),
        RuleSetting("JULIA-SYNTAX", true, Fail),
        RuleSetting("JULIA-CLOSING-PAREN-PLACEMENT", true, Fail),
        RuleSetting("JULIA-JET-POSSIBLE-ERROR", true, Fail),
        RuleSetting("JULIA-EMPTY-CATCH", true, Report),
        RuleSetting("JULIA-DUPLICATE-CODE", true, Report),
        RuleSetting("JULIA-BROAD-CATCH", true, Report),
        RuleSetting("JULIA-UNSIGNALED-ARGUMENT-MUTATION", true, Report),
        RuleSetting("JULIA-GLOBAL-WRITE", true, Report),
        RuleSetting("JULIA-UNREACHABLE-FUNCTION", true, Report),
        RuleSetting("JULIA-NAMING", true, Warn),
        RuleSetting("JULIA-NONCONST-GLOBAL", true, Warn),
        RuleSetting("JULIA-CONST-MUTABLE-REF", true, Warn),
        RuleSetting("JULIA-UNUSED-IMPORT", true, Report),
        RuleSetting("JULIA-DECLARATION-ORDER", true, Warn),
        RuleSetting("JULIA-RETURN-TUPLE", true, Fail),
        RuleSetting("JULIA-PARAMETERS-FAIL", true, Fail),
        RuleSetting("JULIA-FUNCTION-LINES-REPORT", true, Report),
        RuleSetting("JULIA-FUNCTION-LINES-WARN", true, Warn),
        RuleSetting("JULIA-FUNCTION-LINES-FAIL", true, Fail),
        RuleSetting("JULIA-CYCLOMATIC-REPORT", true, Report),
        RuleSetting("JULIA-CYCLOMATIC-WARN", true, Warn),
        RuleSetting("JULIA-CYCLOMATIC-FAIL", true, Fail),
        RuleSetting("ODIN-SYNTAX", true, Fail),
        RuleSetting("ODIN-BUILD-FAILED", true, Fail),
        RuleSetting("ODIN-CLOSING-PAREN-PLACEMENT", true, Fail),
        RuleSetting("ODIN-NAMING", true, Warn),
        RuleSetting("ODIN-NONCONST-GLOBAL", true, Warn),
        RuleSetting("ODIN-UNUSED-IMPORT", true, Report),
        RuleSetting("ODIN-DUPLICATE-CODE", true, Report),
        RuleSetting("ODIN-UNREACHABLE-PROCEDURE", true, Report),
        RuleSetting("ODIN-DECLARATION-ORDER", true, Warn),
        RuleSetting("ODIN-RETURN-TUPLE", true, Fail),
        RuleSetting("ODIN-PARAMETERS-WARN", true, Warn),
        RuleSetting("ODIN-PARAMETERS-FAIL", true, Fail),
        RuleSetting("ODIN-FUNCTION-LINES-REPORT", true, Report),
        RuleSetting("ODIN-FUNCTION-LINES-WARN", true, Warn),
        RuleSetting("ODIN-FUNCTION-LINES-FAIL", true, Fail),
        RuleSetting("ODIN-CYCLOMATIC-REPORT", true, Report),
        RuleSetting("ODIN-CYCLOMATIC-WARN", true, Warn),
        RuleSetting("ODIN-CYCLOMATIC-FAIL", true, Fail),
        RuleSetting("ODIN-ALLOCATION-IMPLICIT", true, Warn),
        RuleSetting("ODIN-ALLOCATION-UNKNOWN", true, Fail),
        RuleSetting("ODIN-ALLOCATION-CONTEXT", true, Warn),
        RuleSetting("ODIN-ALLOCATION-HEAP", true, Warn),
        RuleSetting("ODIN-ALLOCATION-TEMPORARY", true, Report),
        RuleSetting("ODIN-ALLOCATION-CUSTOM", true, Report),
        RuleSetting("ODIN-ALLOCATION-DYNAMIC-GROWTH", true, Report),
        RuleSetting("ODIN-ALLOCATION-ARENA", true, Warn),
        RuleSetting("ODIN-ALLOCATION-HIDDEN", true, Warn),
        RuleSetting("ODIN-ALLOCATION-POLICY-DRIFT", true, Fail),
        RuleSetting("JULIA-DOC-MISSING", true, Fail),
        RuleSetting("ODIN-DOC-MISSING", true, Fail),
        RuleSetting("MARKDOWN-SINGLE-H1", true, Warn),
        RuleSetting("MARKDOWN-HEADING-LEVELS", true, Warn),
        RuleSetting("MARKDOWN-CODE-FENCE-LANGUAGE", true, Warn),
        RuleSetting("MARKDOWN-RELATIVE-LINK", true, Warn),
        RuleSetting("MARKDOWN-IMAGE-ALT-TEXT", true, Warn),
    ],
    NamingSettings([
        convention.language == :julia && convention.kind == :function ?
            NamingConvention(
                convention.language,
                convention.kind,
                convention.casing;
                allow_leading_underscore=convention.allow_leading_underscore,
                allow_trailing_bang=convention.allow_trailing_bang,
                allow_constructor_names=true,
                ignored_names=convention.ignored_names,
                ignored_patterns=convention.ignored_patterns) : convention
        for convention in default_naming_settings().conventions
    ]),
    JetSettings([
        JetEntryPoint(
            "analyzer-cli",
            "src/OdinJuliaAnalysis.jl",
            OdinJuliaAnalysis.main,
            (Vector{String},)),
    ]),
    OdinBuildSettings([
        OdinBuildTarget(
            "analysis-engine",
            "odin_engine",
            "odin-analysis-engine",
            ["-vet", "-strict-style", "-disallow-do", "-warnings-as-errors"]),
    ]),
    ReturnTupleSettings(2, 2),
    ParameterCountSettings(8, 5, 8),
    FunctionMetricSettings(
        default_function_metric_settings().julia_lines,
        default_function_metric_settings().odin_lines,
        default_function_metric_settings().julia_cyclomatic,
        default_function_metric_settings().odin_cyclomatic,
        ReviewedComplexity[
            ReviewedComplexity(
                "julia-declaration-naming-visitor",
                "src/julia_engine/JuliaEngine.jl",
                :julia,
                "collect_naming!",
                :cyclomatic_complexity,
                "The recursive syntax visitor keeps declaration scope " *
                    "transitions together.";
                response=Report),
        ]),
    default_architecture_settings(),
    AllocationSettings(
        KnownAllocatingProcedure[],
        [
            AllocatorSourcePattern("context.allocator", :context),
            AllocatorSourcePattern("context.temp_allocator", :temporary),
            AllocatorSourcePattern("heap.allocator()", :heap),
            AllocatorSourcePattern("data.allocator", :custom),
        ],
        ReviewedAllocationPolicy[
            ReviewedAllocationPolicy(
                "analysis-test-metrics-arena",
                "odin_engine/main_tests.odin",
                "odin_engine_test_procedure_metrics",
                :arena,
                "A test-lifetime arena owns parser fixtures and analysis results.";
                operation="arena_init_static",
                target="arena",
                certainty=:definite,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-test-allocation-arena",
                "odin_engine/main_tests.odin",
                "odin_engine_test_allocation_classification",
                :arena,
                "A test-lifetime arena owns parser fixtures and analysis results.";
                operation="arena_init_static",
                target="arena",
                certainty=:definite,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-test-syntax-arena",
                "odin_engine/main_tests.odin",
                "odin_engine_test_syntax_failure",
                :arena,
                "A test-lifetime arena owns parser fixtures and analysis results.";
                operation="arena_init_static",
                target="arena",
                certainty=:definite,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-arena-backing",
                "odin_engine/main.odin",
                "main",
                :arena,
                "One static virtual arena backs all analyzer allocations.";
                operation="arena_init_static",
                target="analysis_arena",
                certainty=:definite,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-symbol-inventory-growth",
                "odin_engine/main.odin",
                "append_symbol",
                :dynamic_growth,
                "The analysis arena owns the declaration inventory.";
                operation="append",
                target="data.symbols",
                certainty=:potential,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-abi-type-growth",
                "odin_engine/main.odin",
                "append_abi_types",
                :dynamic_growth,
                "The analysis arena owns normalized ABI type inventories.";
                operation="append",
                target="result",
                certainty=:potential,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-interop-type-storage",
                "odin_engine/main.odin",
                "append_interop_signature",
                :custom,
                "Interop parameter and result types use the analysis allocator.";
                operation="make",
                allocator_source="data.allocator",
                certainty=:definite,
                response=Ignore,
                minimum_matches=2,
                maximum_matches=2),
            ReviewedAllocationPolicy(
                "analysis-interop-inventory-growth",
                "odin_engine/main.odin",
                "append_interop_signature",
                :dynamic_growth,
                "The analysis arena owns normalized interop signatures.";
                operation="append",
                target="data.interop_signatures",
                certainty=:potential,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-global-finding-growth",
                "odin_engine/main.odin",
                "check_nonconst_global",
                :dynamic_growth,
                "The analysis arena owns global-policy findings.";
                operation="append",
                target="data.findings",
                certainty=:potential,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-allocation-finding-growth",
                "odin_engine/main.odin",
                "append_allocation_finding",
                :dynamic_growth,
                "The analysis arena owns allocation findings.";
                operation="append",
                target="data.findings",
                certainty=:potential,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-procedure-inventory-growth",
                "odin_engine/main.odin",
                "register_procedure_scopes",
                :dynamic_growth,
                "The analysis arena owns procedure scopes, metrics, and bodies.";
                operation="append",
                certainty=:potential,
                response=Ignore,
                minimum_matches=3,
                maximum_matches=3),
            ReviewedAllocationPolicy(
                "analysis-body-token-storage",
                "odin_engine/main.odin",
                "canonical_body_tokens",
                :custom,
                "Canonical body tokens use the caller-provided analysis allocator.";
                operation="make",
                target="[dynamic]string",
                allocator_source="allocator",
                certainty=:definite,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-body-token-growth",
                "odin_engine/main.odin",
                "canonical_body_tokens",
                :dynamic_growth,
                "The analysis arena owns canonical body tokens.";
                operation="append",
                target="tokens",
                certainty=:potential,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-documentation-finding-growth",
                "odin_engine/main.odin",
                "check_procedure_documentation",
                :dynamic_growth,
                "The analysis arena owns documentation findings.";
                operation="append",
                target="data.findings",
                certainty=:potential,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-import-symbol-growth",
                "odin_engine/main.odin",
                "append_import_symbol",
                :dynamic_growth,
                "The analysis arena owns imported declaration symbols.";
                operation="append",
                target="data.symbols",
                certainty=:potential,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-import-edge-growth",
                "odin_engine/main.odin",
                "append_import_edge",
                :dynamic_growth,
                "The analysis arena owns import edges.";
                operation="append",
                target="data.imports",
                certainty=:potential,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-reference-growth",
                "odin_engine/main.odin",
                "append_reference",
                :dynamic_growth,
                "The analysis arena owns identifier references.";
                operation="append",
                target="data.references",
                certainty=:potential,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-call-edge-growth",
                "odin_engine/main.odin",
                "append_call_edge",
                :dynamic_growth,
                "The analysis arena owns call graph edges.";
                operation="append",
                target="data.call_edges",
                certainty=:potential,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-procedure-scope-storage",
                "odin_engine/main.odin",
                "check_allocations",
                :custom,
                "Procedure scopes use the caller-provided analysis allocator.";
                operation="make",
                target="[dynamic]Procedure_Scope",
                allocator_source="allocator",
                certainty=:definite,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-parenthesis-finding-growth",
                "odin_engine/main.odin",
                "close_parenthesis_frame",
                :dynamic_growth,
                "The analysis arena owns closing-parenthesis findings.";
                operation="append",
                target="findings",
                certainty=:potential,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-parenthesis-frame-storage",
                "odin_engine/main.odin",
                "check_closing_parentheses",
                :custom,
                "The parenthesis stack uses the caller-provided analysis allocator.";
                operation="make",
                target="[dynamic]Parenthesis_Frame",
                allocator_source="allocator",
                certainty=:definite,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-parenthesis-frame-growth",
                "odin_engine/main.odin",
                "check_closing_parentheses",
                :dynamic_growth,
                "The analysis arena owns the transient parenthesis stack.";
                operation="append",
                target="frames",
                certainty=:potential,
                response=Ignore),
            ReviewedAllocationPolicy(
                "analysis-file-inventory-storage",
                "odin_engine/main.odin",
                "analyze_file",
                :custom,
                "File analysis inventories use the caller-provided allocator.";
                operation="make",
                allocator_source="allocator",
                certainty=:definite,
                response=Ignore,
                minimum_matches=6,
                maximum_matches=6),
            ReviewedAllocationPolicy(
                "analysis-summary-storage",
                "odin_engine/main.odin",
                "main",
                :custom,
                "File summaries are allocated from the process analysis arena.";
                operation="make",
                target="[]File_Summary",
                allocator_source="analysis_allocator",
                certainty=:definite,
                response=Ignore),
        ]),
    ReportSettings(:auto, 50, 50),
    AnalysisExtension[],
    DuplicateCodeSettings(false, 40, 6, 2, String[], ReviewedClonePolicy[]),
    ResourceLifetimeSettings(false, ResourceLifetimeContract[]),
    SecuritySettings(
        false,
        SecurityCallContract[],
        SecurityCallContract[],
        SecurityCallContract[]),
    CoverageSettings(false, String[], 20),
    DocumentationSettings(r"\S", r"\S"),
    CallRootSettings([
        CallRootEntryPoint(
            "odin-test:greeting_test",
            :odin,
            "greeting_test",
            "The Odin test runner invokes this procedure through @(test)."),
    ]))